version: '3.9'
services:
  app:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - unifyid-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: unifyid
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - unifyid-net


  redis:
    image: redis:7
    networks:
      - unifyid-net

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    networks:
      - unifyid-net

volumes:
  db-data:

networks:
  unifyid-net:

# Builds Laravel, Postgres, Redis, React in isolated containers
# Mounts code for live reload
# All services share unifyid-net for internal communication