version: "3.8"

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./unifyId/backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: unifyid_saas
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_pass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./unifyId/backend:/var/www/html
      - ./unifyId/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  node:
    image: node:18
    container_name: frontend_node
    working_dir: /usr/src/app
    volumes:
      - ./unifyId/front-end:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
